// Code generated by go generate; DO NOT EDIT.
package main

import "github.com/fieldryand/goflow/core"
import "github.com/fieldryand/goflow/jobs"

func flow(job string) func() *core.Job {
	switch job {
		case "example": return jobs.ExampleJob
	default:
		return nil
	}
}
